name: Build
on: workflow_dispatch
jobs:
  Windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Haxe
        uses: krdlab/setup-haxe@38fd78cc3a7960b281cf4a33a63a9c1543ac4598
        with:
          haxe-version: 4.3.4

      - name: Install Libraries
        run: |
          mkdir -p "%HAXELIB_ROOT%"
          haxelib setup "%HAXELIB_ROOT%"
          haxelib install lime 7.9.0 --quiet
          haxelib install openfl --quiet
          haxelib install flixel 4.9.0 --quiet
          haxelib install hxcpp --quiet
          haxelib install flixel-tools --quiet
          haxelib install flixel-ui --quiet
          haxelib install flixel-addons 2.10.0 --quiet
          haxelib install hscript --quiet
          haxelib git faxe https://github.com/uhrobots/faxe --quiet
          haxelib git polymod https://github.com/MasterEric/polymod.git --quiet
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc --quiet
          haxelib git extension-webm https://github.com/Sirox228/extension-webm --quiet
          haxelib git linc_luajit https://github.com/Daninnocent/linc_luajit.git --quiet
          haxelib install actuate 
          haxelib list

      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION
          
      - name: Configure Windonws
        run: |
          haxelib run lime setup -alias -y
          haxelib set openfl 9.1.0
          haxelib set lime 7.9.0
          haxelib set flixel 4.11.0
          haxelib set flixel-addons 3.0.2
          haxelib set hxcpp 4.2.1
          
      - name: Building
        run: haxelib run lime build windows

      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: Windows Build
          path: export\release\windows\bin\*
          if-no-files-found: error
          
  Android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r21e

      - name: Setup Java JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Setup Haxe
        uses: krdlab/setup-haxe@38fd78cc3a7960b281cf4a33a63a9c1543ac4598
        with:
          haxe-version: 4.2.5

      - name: Install Haxelib
        run: |
          mkdir -p "%HAXELIB_ROOT%"
          haxelib setup "%HAXELIB_ROOT%"
          haxelib install lime 7.9.0 --quiet
          haxelib install openfl --quiet
          haxelib install flixel 4.9.0 --quiet
          haxelib install hxcpp --quiet
          haxelib install flixel-tools --quiet
          haxelib install flixel-ui --quiet
          haxelib install flixel-addons 2.10.0 --quiet
          haxelib install hscript --quiet
          haxelib git faxe https://github.com/uhrobots/faxe --quiet
          haxelib git polymod https://github.com/MasterEric/polymod.git --quiet
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc --quiet
          haxelib git extension-webm https://github.com/Sirox228/extension-webm --quiet
          haxelib git linc_luajit https://github.com/Daninnocent/linc_luajit.git --quiet
          haxelib install actuate 
          haxelib list

      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION

      - name: Setup Lime
        run: |
          haxelib run lime setup -alias -y
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_HOME
          haxelib run lime config JAVA_HOME $JAVA_HOME
          haxelib run lime config ANDROID_SETUP true
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

      - name: Compile
        run: haxelib run lime build android --app-version="4.0.0-${{ github.run_id}}"

      - name: Publish Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: Android Build
          path: export/release/android/bin/app/build/outputs/apk/debug
         if-no-files-found: error
